version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGODB_USER=juan
      - MONGODB_DATABASE=juan
      - MONGODB_PASS=juan
    volumes:
      - pgdata:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
volumes:
  pgdata:
    driver: local